version: '3.7'

services:
  crypto-port-service:
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
    restart: always
    command: node ./main.js
